name: Terraform Plan
description: Run Terraform init and plan
inputs:
  working-directory:
    description: Directory containing Terraform files
    required: true

runs:
  using: composite

  steps:
    - name: Terraform Init
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: terraform init

    - name: Terraform Plan
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: terraform plan
