name: 00.Terraform_Env_Variables
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  Terraform_Env_test:
    runs-on: ubuntu-22.04
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_USE_OIDC: true

    steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Check Azure Login
          run: |
            echo "ARM_CLIENT_ID: $ARM_CLIENT_ID"
            echo "ARM_SUBSCRIPTION_ID: $ARM_SUBSCRIPTION_ID"
            echo "ARM_TENANT_ID: $ARM_TENANT_ID"
            echo ${{ toJSON(vars) }}

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v3
        - name: Terraform Init
          working-directory: ./terraform/01.Env_Module
          run: terraform init
        - name: Terraform Validate
          working-directory: ./terraform/01.Env_Module
          run: terraform validate
        - name: Terraform Plan
          working-directory: ./terraform/01.Env_Module
          run: terraform plan
        - name: Terraform Apply
          working-directory: ./terraform/01.Env_Module
          run: terraform apply -auto-approve
