name: 06.Call Child Workflow
on:
 workflow_dispatch:
jobs:
  call-deployment:
    uses: ./.github/workflows/05.gitactions-full.yaml
    with:
      resource_group: "rg-resgrp"
      location: "uksouth"
