name: crisscross
on:
  workflow_dispatch:
jobs:
  image1-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [ amd64,arm64 ]
    steps:
     - name: buildimage
       run: echo "building image1 ${{ matrix.arch }}"
  
  image2-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [ amd64,arm64 ]
    steps:
     - name: buildimage
       run: echo "building image2 ${{ matrix.arch }}"

  image3-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [ amd64,arm64 ]
    steps:
     - name: buildimage
       run: echo "building image3 ${{ matrix.arch }}"
    
  planjob1:
    runs-on: ubuntu-latest
    needs:  
      - image1-build
      - image2-build
      - image3-build
    steps: 
       - name: planjob1
         run: echo "plan job1"
  planjob2:
    runs-on: ubuntu-latest
    needs:  
      - image1-build
      - image2-build
      - image3-build
    steps: 
       - name: planjob2
         run: echo "plan job2"
