name: crisscross
on:
  workflow_dispatch:
jobs:
  builldjob:
    runs-on: ubuntu-latest
    steps:
     - name: buildimage1
       run: echo "building image 1"
     - name: buildimage1
       run: echo "building image 2"
     - name: buildimage1
       run: echo "building image 3"
  planjob:
    runs-on: ubuntu-latest
    needs: builldjob
    steps: 
       - name: planjob1
         run: echo "plan job1"
