name: environment variable
on:
    workflow_dispatch:

env:
    GlobalLevel: "can be used in all jobs"
    MY_AGE: "30"

jobs:
  job1:
    runs-on: ubuntu-latest
    env:
        JobLevel: "can be used in all steps of this job"
        MY_NAME: "John Doe"
    steps:
      - name: Show global env variable
        run: echo "GlobalLevel is ${{ env.GlobalLevel }}"
      - name: Show job env variable
        run: echo "JobLevel is ${{ env.JobLevel }}"
      - name: Show step env variable
        run: echo "MY_AGE is ${{ env.MY_AGE }}"
      - name: Test JJ
        run: echo "here is a env variable ${{ env.MY_NAME}}"
