name: environment variable
on:
    workflow_dispatch:
      inputs:
        ENVIRONMENT:
          description: "Choose an environment"
          required: true # User must provide a value for an input before the workflow can be started.
          type: choice
          options:
            - "Dev"
            - "Int"
            - "Production"

env:
    DEPLOY_ENV: ${{ inputs.ENVIRONMENT }}

jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      ENV_ONLY_for_job1: "JOB1 VALUE"
    steps:
      - name: FiRST JOB
        run: echo "GlobalLevel is ${{ env.DEPLOY_ENV }}"
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: SECOND JOB
        run: |
          echo "GlobalLevel is ${{ env.DEPLOY_ENV }}"
          echo "if Job1 value is available in Job2: ${{ env.ENV_ONLY_for_job1 }}"
