name: GitHub Actions Learning

on:
  push:                         # PUSH AND PULL BRANCH
    branches:
      - feature
  workflow_dispatch:           # MANUAL TRIGGER
    inputs:
      message:
        description: "Message to print"
        required: true
        type: string
        default: "Hello GitHub Actions"
jobs:
  'learn_JOB_TITLE':
    runs-on: ubuntu-latest
    steps:
      - name: Show trigger
        run: echo "Triggered by ${{ github.event_name }}"

      - name: Show branch
        run: echo "Branch is ${{ github.ref }}"

      - name: Show input
        run: echo "Message is ${{ inputs.message }}"
