name: uses with input

on:
  workflow_dispatch:
    inputs:
      message:
        description: "Message to print"
        required: true
        type: string
        default: "Hello GitHub Actions JJ"

jobs:
  'with_inputs':
    runs-on: ubuntu-latest
    steps:
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: running simple script
        run: |
            echo "helo from node"
            echo "hello from $inputs.message"
